# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.CharField(max_length=3, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('master', models.CharField(max_length=30, verbose_name='主人')),
                ('brand', models.CharField(max_length=30, verbose_name='品牌')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('screen_size', models.FloatField(verbose_name='屏幕尺寸')),
            ],
        ),
    ]
